# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_unique', models.CharField(help_text='Phone Number of the Complainee', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name_plural': 'PasswordsGeneration',
                'verbose_name': 'PasswordGeneration',
                'ordering': ['-created_at'],
            },
        ),
    ]
